# fly.toml app configuration file generated for new-sneaker-api on 2025-06-24T11:57:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-sneaker-api'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  app = './bin/rails server'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/sneaker-api/public'
  url_prefix = '/'
